baseURL = "https://blissful-nightingale-12edfd.netlify.app"
title = "Minjoon's codepark"
theme = "hugo-clarity"

pluralizeListTitles = false

# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 9

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[params]
description = "This is my personal blog about tech."
author = "Minjoon Hong"
keywords = []
images = []
enforceLightMode = true
codeLineNumbers = true
codeMaxLines = 50
